apiVersion: v1
kind: Service
metadata:
  name: nextjs-app
  namespace: default
  labels:
    app: nextjs-app
  annotations:
    # Service type annotation for ALB
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: ClusterIP # ALB Ingress controller will handle external access
  selector:
    app: nextjs-app
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: http
      protocol: TCP
